#ifndef TASK_TYPE_HPP
#define TASK_TYPE_HPP
#include "task.hpp"

enum class Task::TaskType
{
    FIRST_GRAPH_ANALYSIS = 1,
    SECOND_BUILDING_LOGICAL_TABLE = 2,
    THIRD_SK = 3,
    FOURTH_ENCODING_AND_DECODING_TASK = 4,
    SEVENTH_ENCODING_AND_DECODING_TRANSMISSION_TASK = 7
};

#endif // TASK_TYPE_HPP